### ISSUE TITLE
Always Bluetooth error connection

### ISSUE THREAD

**Issue by djdevil** [TheBazeman/AM43-Blinds-Drive#1]
Hi I ran the guide as written in the readme file, I created the service and the web service but it cannot connect via Bluetooth! Where I am wrong I also entered the mac address in the ini file!  can you help me thanks

**Comment by TheBazeman** [comment]
Hi,

Can you show me the output of “service AOK-AM43 status” and “blescan”?

Did you use the install path specified as in the code so it can find the ini file? (/A-OK_AM43_Blind_Drive/)

Met vriendelijke groet,

Bas Bahlmann

Van: djdevil [mailto:notifications@github.com]
Verzonden: maandag 10 februari 2020 07:22
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [TheBazeman/A-OK-AM43-Blinds-Drive] Always Bluetooth error connection (#1)


Hi I ran the guide as written in the readme file, I created the service and the web service where I am wrong I also entered the mac address in the ini file! can you help me thanks

**Comment by djdevil** [comment]
Hi, thx for reply this my error!

10-02-2020 18:21:54 Scanning for bluetooth devices....
10-02-2020 18:21:56 Scanning for bluetooth devices....
10-02-2020 18:21:56 ERROR SCANNING FOR ALL BTLE Devices, trying to Open the blinds anyway....
10-02-2020 18:21:56 Please check any open connections to the blinds motor and close them, the Blinds Engine App perhaps?
[2020-02-10 18:21:56,128] ERROR in app: Exception on /AM43BlindsAction/Open [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "AOK-AM43.py", line 84, in AM43BlindsAction
    for AM43BlindsDevice in config['AM43_BLE_Devices']:
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'AM43_BLE_Devices'
192.168.1.5 - - [10/Feb/2020 18:21:56] "GET /AM43BlindsAction/Open HTTP/1.1" 500 -

**Comment by djdevil** [comment]
This my service status and my ini file.

`● AOK-AM43.service - AOK-AM43 Web service
   Loaded: loaded (/lib/systemd/system/AOK-AM43.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-02-10 18:45:44 CET; 5s ago
 Main PID: 32411 (python3)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/AOK-AM43.service
           └─32411 /usr/bin/python3 /home/pi/A-OK_AM43_Blind_Drive/AOK-AM43.py

Feb 10 18:45:44 raspberrypi systemd[1]: Started AOK-AM43 Web service.
Feb 10 18:45:45 raspberrypi python3[32411]: TERM environment variable not set.
Feb 10 18:45:45 raspberrypi python3[32411]:  * Serving Flask app "AOK-AM43" (lazy loading)
Feb 10 18:45:45 raspberrypi python3[32411]:  * Environment: production
Feb 10 18:45:45 raspberrypi python3[32411]:    WARNING: This is a development server. Do not use it in
Feb 10 18:45:45 raspberrypi python3[32411]:    Use a production WSGI server instead.
Feb 10 18:45:45 raspberrypi python3[32411]:  * Debug mode: off
Feb 10 18:45:45 raspberrypi python3[32411]:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
`

ini file

`[AM43_BLE_Devices]
Blinds1=02:A0:07:6A:94:8D
Blinds2=xx:xx:xx:xx:xx:xx
Blinds3=xx:xx:xx:xx:xx:xx
`

**Comment by djdevil** [comment]
pi@raspberrypi:~ $ sudo hcitool lescan

LE Scan ...
64:1C:AE:03:13:78 (unknown)
64:1C:AE:03:13:78 [TV] Samsung Frame Series (55
7B:4A:E1:6E:6D:F3 (unknown)
7B:4A:E1:6E:6D:F3 (unknown)
02:A0:07:6A:94:8D (unknown)
**02:A0:07:6A:94:8D Tenda Bagno**
7D:4E:E9:AF:EB:A4 (unknown)
7C:94:FA:B9:98:07 (unknown)
5A:FC:BF:0B:77:D5 (unknown)
5A:FC:BF:0B:77:D5 (unknown)
5C:F9:38:B3:DC:32 (unknown)
5C:F9:38:B3:DC:32 (unknown)
7D:4E:E9:AF:EB:A4 (unknown)
80:EA:CA:88:D7:22 (unknown)

**Comment by djdevil** [comment]
my error patch error file .ini sorry now work perfect
is normal long delay from command?

**Comment by TheBazeman** [comment]
Hi, glad it’s working. Yes is normal, i do a 10 second blescan to search for devices

Met vriendelijke groet,

Bas Bahlmann

Van: djdevil [mailto:notifications@github.com]
Verzonden: maandag 10 februari 2020 21:43
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Bas Bahlmann <bas@bahlmann.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [TheBazeman/A-OK-AM43-Blinds-Drive] Always Bluetooth error connection (#1)


Did you use the install path specified as in the code so it can find the ini file?
my error patch error sorry now work perfect?
is normal long delay from command?
