### ISSUE TITLE
Integrate Domoticz

### ISSUE THREAD

**Issue by djdevil** [TheBazeman/AM43-Blinds-Drive#3]
Hello so following your work and to say the least is fantastic, added with the addition of the percentage and the state.
I wanted to know if there is the possibility to integrate it in Domoticz, I am trying to create a lua script in the meantime but I am waiting for the release with the MQTT version.

**Comment by TheBazeman** [comment]
Hi, thanks a lot.

MQTT support will take a while as I have zero experience with MQTT yet. I am using Zipato Zipabox as homeautomation as of 2013 with z-wave devices only which works very well. Most home automation solutions can/should work with the JSON output this script returns, your Domoticz should have that option too I saw through google.

Met vriendelijke groet,

Bas Bahlmann

Van: djdevil [mailto:notifications@github.com]
Verzonden: zaterdag 15 februari 2020 18:57
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [TheBazeman/A-OK-AM43-Blinds-Drive] Integrate Domoticz (#3)


Hello so following your work and to say the least is fantastic, added with the addition of the percentage and the state.
I wanted to know if there is the possibility to integrate it in Domoticz, I am trying to create a lua script in the meantime but I am waiting for the release with the MQTT version.

**Comment by AdamWeglarz** [comment]
I have made integration with domoticz.

https://www.domoticz.com/forum/viewtopic.php?f=56&t=36025
