### ISSUE TITLE
Finding out the device MAC address...

### ISSUE THREAD

**Issue by alexcf** [TheBazeman/AM43-Blinds-Drive#4]
What’s the best way to get the MAC address of the devices?

**Comment by TheBazeman** [comment]
Hi,

Give the blind controller(s) a proper name in the app on your phone, exit the app and then run “blescan” on your raspberry. The MAC addresses should be visible for all your blind controllers within range.

Good luck,
-Bas

Van: alexcf [mailto:notifications@github.com]
Verzonden: zaterdag 28 maart 2020 01:09
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [TheBazeman/A-OK-AM43-Blinds-Drive] Finding out the device MAC address... (#4)


What’s the best way to get the MAC address of the devices?

**Comment by TheBazeman** [comment]
Adjusted the readme
