### ISSUE TITLE
light sensor not working

### ISSUE THREAD

**Issue by ghost** [TheBazeman/AM43-Blinds-Drive#7]
fix:

change
            LightPct = data[3]
to
            LightPct = data[4]
in AOK-AM43.py

**Comment by dr-ni** [comment]
nice - now i have brightness values between 0 an 8 rather than always 0

**Comment by TheBazeman** [comment]
I have changed it in the code, thanks!

**Comment by dr-ni** [comment]
is it possible that the light value is stored as short int  (2 bytes, data[4] and data[5])?
values betweenk 0 and 8 are not that much as expectet?
found this in the projec thttps://github.com/binsentsu/am43-ctrl in inam43.js

 if (batteryNotificationIdentifier === notificationIdentifier) {
                        //battery is hexadecimal on position 14, 2 bytes
                        let batteryHex = strBfr.substr(14, 2);
                        //convert hex number to integer
                        let batteryPercentage = parseInt(batteryHex, 16);
                        self.writeLog('Bat %: ' + batteryPercentage);
                        self.batterypercentage = batteryPercentage;
                        self.batterysuccess = true;

                        //write cmd to enable light notification
                        characteristic.write(Buffer.from(HEY_KEY_LIGHT_REQUEST, "hex"), true);
                    } else if (lightNotificationIdentifier === notificationIdentifier) {
                        //light is byte 4 (ex. 9a aa 02 00 00 32)
                        let lightHex = strBfr.substr(8, 2);
                        //convert to integer
                        let lightPercentage = parseInt(lightHex, 16);
                        self.writeLog('Light %: ' + lightPercentage);
                        self.lightpercentage = lightPercentage;
                        self.lightsuccess = true;

                        //write cmd to get position
                        characteristic.write(Buffer.from(HEY_KEY_POSITION_REQUEST, "hex"), true);
                    } else if (positionNotificationIdentifier === notificationIdentifier) {
                        //position is byte 6: 9a a7 07 0f 32 4e 00 00 00 30 79
                        let positionHex = strBfr.substr(10, 2);
                        //convert to integer
                        let positionPercentage = parseInt(positionHex, 16);
                        self.writeLog('Position %: ' + positionPercentage);
                        self.positionpercentage = positionPercentage;
                        self.positionsuccess = true;
                        self.reevaluateState();
                    }
