### ISSUE TITLE
ERROR: Cannot find ini file

### ISSUE THREAD

**Issue by roblomq** [TheBazeman/AM43-Blinds-Drive#8]
Hi,

Thanks for your work. I'm trying to get this up and running but I keep getting the following error:

sudo python /home/pi/domoticz/scripts/python/AOK-AM43.py
  File "/home/pi/domoticz/scripts/python/AOK-AM43.py", line 57
    print("ERROR: Cannot find ini file: " + inifilepath + "! Correct the path in this script or put the ini file in the correct directory. Exiting", flush=True)
                                                                                                                                                          ^
SyntaxError: invalid syntax

The ini file it there for sure so probably there is something else wrong but can't figure out what.

**Comment by TheBazeman** [comment]
Hi,

Just place the original script and your created inifile in the original directory "/A-OK_AM43_Blind_Drive/" and start from there. Must be a typo or something.

Kind regards,
-Bas

Van: roblomq [mailto:notifications@github.com]
Verzonden: donderdag 9 juli 2020 02:12
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [TheBazeman/A-OK-AM43-Blinds-Drive] ERROR: Cannot find ini file (#8)


Hi,

Thanks for your work. I'm trying to get this up and running but I keep getting the following error:

sudo python /home/pi/domoticz/scripts/python/AOK-AM43.py
File "/home/pi/domoticz/scripts/python/AOK-AM43.py", line 57
print("ERROR: Cannot find ini file: " + inifilepath + "! Correct the path in this script or put the ini file in the correct directory. Exiting", flush=True)
^
SyntaxError: invalid syntax

The ini file it there for sure so probably there is something else wrong but can't figure out what.

**Comment by roblomq** [comment]
To be sure, that means the "/A-OK_AM43_Blind_Drive/" folder is in the root of the pi, on the same level as the "home" folder for example? If yes, I already did that but gives the same error.

The service is running but is that needed for the script?

**Comment by ghost** [comment]
maybe because running in python2 ?

try:
sudo python3 /home/pi/domoticz/scripts/python/AOK-AM43.py

**Comment by dr-ni** [comment]
yes -  this solved the problem for me :-)

**Comment by TheBazeman** [comment]
Adjusted the readme and explained it to prevent this. I cannot program it because it is failing at pre-compiling within Python.

**Comment by roblomq** [comment]
Funny that this issue is closed because someone says it solved his issue while the topic starter didn't even test it yet.

**Comment by TheBazeman** [comment]
I have reproduced the error and added comments to the readme. Problem solved

Met vriendelijke groet,

Bas Bahlmann

Van: roblomq [mailto:notifications@github.com]
Verzonden: dinsdag 14 juli 2020 10:19
Aan: TheBazeman/A-OK-AM43-Blinds-Drive <A-OK-AM43-Blinds-Drive@noreply.github.com>
CC: Bas Bahlmann <bas@bahlmann.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [TheBazeman/A-OK-AM43-Blinds-Drive] ERROR: Cannot find ini file (#8)


Funny that this issue is closed because someone says it solved his issue while the topic starter didn't even test it yet.

**Comment by roblomq** [comment]
When I run

sudo python3 /home/pi/domoticz/scripts/python/AOK-AM43.py

I get te following

` * Serving Flask app "AOK-AM43" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/python/AOK-AM43.py", line 252, in <module>
    app.run(host='0.0.0.0') #Listen to all interfaces  #,debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
`

**Comment by dr-ni** [comment]
Is another server is still running?
try:
ps -fA | grep python
and post the result

**Comment by roblomq** [comment]
`root     26673     1 21 20:43 ?        00:00:09 /usr/bin/python3 /home/pi/domoticz/scripts/python/AOK-AM43.py`

So indeed you get this traceback if it is already running.
I've managed to get it working now and am trying to control it by Domoticz. I've got a question, is the service started up at a reboot or do I need to add a start command somewhere the service is started at boot.

**Comment by dr-ni** [comment]
you need to start it
e.g. by cron:
sudo crontab -e
#add this:
@reboot /usr/bin/python3 /home/pi/domoticz/scripts/python/AOK-AM43.py > /dev/null 2>&1 &

or add this to /etc/rc.local before exit 0:
/usr/bin/python3 /home/pi/domoticz/scripts/python/AOK-AM43.py > /dev/null 2>&1 &
